### ISSUE TITLE
Все скрипты (если есть) подключены непосредственно перед `</body>`.

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#11]
Карты спокойно можно перенести под конец. (Но подключать первее main)
https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/index.html#L9

**Comment by catch-a-chalk** [comment]
Скрипт перенесен перед main.min.js.
