### ISSUE TITLE
Грубые ошибки в разметке отсутствуют

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#12]
[Удаляем](https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/index.html#L432:L481) комментарии. При отдаче такого клиенту будет выглядеть очень непрофессионально

**Comment by baileys-li** [comment]
Убрать [предзагрузку WOFF шрифтов](https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/index.html#L12-L13)

Ты заставляешь всех пользователей грузить первоочередно 25кб шрифтов которые [96%](https://caniuse.com/woff2) вообще никогда не понадобятся 
![image](https://user-images.githubusercontent.com/47776594/179804928-55661ff2-e0d5-489e-94c6-1edea9807c46.png)

**Comment by catch-a-chalk** [comment]
Комментарии удалены, предзагрузка шрифтов убрана
