### ISSUE TITLE
Около каждого изображения в HTML должен быть комментарий с её размером для ретины и без ретины

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#13]
Этот кусок тоже нужно прокомментировать. 

https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/index.html#L52-L57

Так же желательно в комментарии написать, чтобы не удаляли другие custom property, а если дизайнер не подготовит фон под все форматы поставить в остальные url одну и ту же ссылку
Дать понятную инструкцию в общем

**Comment by catch-a-chalk** [comment]
Комментарий размеров оставлен
