### ISSUE TITLE
Неправильный путь в шрифтах

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#15]
напоминаю что у тебя итоговые стили в папке build/styles и относительно неё ты и пишешь пути
https://github.com/catch-a-chalk/1872127-antarctica/blob/2abdc31da6c474b70558f55c0a15c56260005b04/source/sass/global/fonts.scss#L27

![image](https://user-images.githubusercontent.com/47776594/179809379-aae07809-6d8d-45e9-82ca-c03718a981bd.png)

**Comment by catch-a-chalk** [comment]
Изменен путь с /source на /build
