### ISSUE TITLE
Код соответствует правилам Stylelint

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#17]
Префикс `-o` вообще для старых Опер, когда Опера была ещё на кастомном движке. В 2022 он не нужен
![image](https://user-images.githubusercontent.com/47776594/179810874-9b0b6402-32ff-4d3c-84ae-2e198c6ea806.png)

https://github.com/catch-a-chalk/1872127-antarctica/runs/7394882628?check_suite_focus=true#step:4:138

**Comment by catch-a-chalk** [comment]
Неактуальное свойство убрано
