### ISSUE TITLE
В коде продакшн-версии проекта нет файлов, модулей и частей кода, которые не используются, включая, закомментированные участки кода

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#20]
Модалки из шаблона нигде не используются, это просто некрокод, который идёт пользователю 
https://github.com/catch-a-chalk/1872127-antarctica/blob/b0b81491537833f3b53ad8061ffa41e7a04fe77a/source/js/main.js#L18-L20

**Comment by catch-a-chalk** [comment]
Неиспользуемые строки кода убраны
