### ISSUE TITLE
В CSS отсутствует !important

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#22]
Я понимаю что он из шаблона, но этот класс нигде не используется, поэтому это не только противоречит критерию, но и мусор
https://github.com/catch-a-chalk/1872127-antarctica/blob/13875e811e390f48978b178bddf201b1aea0e8ec/source/sass/global/utils.scss#L20-L26

**Comment by catch-a-chalk** [comment]
Закрыто через PR
