### ISSUE TITLE
Форма недоделана

### ISSUE THREAD

**Issue by baileys-li** [catch-a-chalk/1872127-antarctica#7]
* Отличается стилизация. 
* Нет кастомного чекбокса
* Нет валидации формы. Например сделать телефон, email телефон `required`. Так же не хватает [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)
![image](https://user-images.githubusercontent.com/47776594/179049726-36f8f1cf-2cbc-4b60-add5-93aec9f0e960.png)

**Comment by catch-a-chalk** [comment]
Готово Исправил цвет, добавил чек-бокс, внес автозаполнение и обязательные поля
